### ISSUE TITLE
question on the pooled CI for AUC from mivalext_lr() function, extra square rooted? 

### ISSUE THREAD

**Issue by yiyunyiyun** [mwheymans/psfmi#1]
I have an imputated data with several nonmissing and not-imputated variables. However, I realised when I use mivalext_lr() to obtain pooled AUC and 95% CI of my logistic regression, the pooled 95% CI is bigger then I get from individual imputated data, (which are the same as the variable used was not imputated), and actually exactly the square root of the CI upper and lower limit obtained from each imputated data set. I understand I should pool AUC after logit transformation with Rubin's rule, integrating the variance of each AUC itself and the variance between imputation. So I tried to look into the source code, and added some print out command, the variate between each imputation (b.roc.logit) truly print out as 0, but I felt the p.se.roc.logit had an extra sqrt.... Can someone help me to take a look? unless it supposed to have bigger SE even for not imputated variables after pooling..... I tried psfmi_perform() in the same package, got the same big CI.

**Comment by mwheymans** [comment]
This problem is solved in the new 0.5.0 version of the package where the mivalext_lr function calculates the pooled AUC with the pool_auc function.
