### ISSUE TITLE
incorrect p-values?

### ISSUE THREAD

**Issue by katybarry** [mwheymans/psfmi#3]
Ok, so i performed the pooled logistic regression model in order to pick out my predictor variables using the forward approach. The ORs seem correct to me based off of other analyses but I find the p-values very strange because according to the 95% CI, many of the variables are not significantly associated with my outcome, but the p-values tell another story, and i think there is a problem with my p-values, but I am not sure what I did or what needs to be changed in order to get the correct p-values. here is my code and my results:

Code :

 

pool_lr <- psfmi_lr(data=dataset_mom, nimp=25, impvar="x_imputation", Outcome="M2_M_PPD", predictors=c("M0_M_nation", "M0_P_nation", "M2_P_PPD", "M00M2_PEREACC",        "mother_medicine", "fchild", "number_household", "relative_poverty"), p.crit = 0.25, cat.predictors = c("M02M_CONGPAT", "Fwanted_child", "Mwanted_child", "M0_P_age", "M2_conflict","M0_siblingbis", "mother_diploma", "dad_profession", "mom_profession","M0_zone", "conab","condp","conbp"), method="D2", keep.predictors = "M02M_CONGPAT", direction = "FW")

and here are the results (found in the link):
![boosting model results](https://user-images.githubusercontent.com/85285630/120623562-1dc0a100-c460-11eb-8003-6063c5d2af0a.png)

any ideas why the p-values would be like this or what i can fix?
thank you so much for your help!

**Comment by mwheymans** [comment]
Issue closed due to mis-interpretation of results by user. Nothing needed to be corrected.
