### ISSUE TITLE
plot the pooled ROC curve

### ISSUE THREAD

**Issue by Wenlei77** [mwheymans/psfmi#4]
The package 'psfmi' is very useful to calculate the pool C-statistic (AUC), with the use of 'pool_performance'. I wondering if there is a way to plot the pooled ROC curve (like below)? Thank you very much!

![ROC-Curve-Plot-for-a-No-Skill-Classifier-and-a-Logistic-Regression-Model](https://user-images.githubusercontent.com/69493763/137414622-5aad3d6d-eb1a-4faf-b38a-0f627a9e7280.png)

**Comment by mwheymans** [comment]
Dear Wenlei,
Thnaks for using the package! I will consider this during the next update.
With best wishes, Martijn
